### ISSUE TITLE
Encountered ERROR while indexing a set of Documents

### ISSUE THREAD

**Issue by wajeeha77** [AnswerDotAI/byaldi#26]
My Document directory has 16 documents, when I tried indexing it, everything went fine till 10th document and then it threw this error, please help!
  
  self.add_to_index(item, store_collection_with_index, doc_id=doc_id, metadata=doc_metadata)
  File "/envs/colpali-vl/lib/python3.10/site-packages/byaldi/colpali.py", line 339, in add_to_index
    raise ValueError(f"Number of doc_ids ({len(doc_ids)}) does not match number of input items ({len(input_items)})")
ValueError: Number of doc_ids (1) does not match number of input items (8)

**Comment by wajeeha77** [comment]
hey, I resolved it myself, just now :) 
It was throwing this error because there was a subdirectory present in the directory of the Set of Documents, after removing it, it ran perfectly, but nevertheless, it should not matter if other folders or other document formats are present in the given directory path, it should be able to pick up on pdfs only and create index from it, and ignore the others, just saying...

thanks for promptly reaching out to help!

**Comment by bclavie** [comment]
> hey, I resolved it myself, just now :)

![image](https://github.com/user-attachments/assets/e33b5a5f-5013-4ddf-b76f-942753804ce5)

> It was throwing this error because there was a subdirectory present in the directory of the Set of Documents, after removing it, it ran perfectly, but nevertheless, it should not matter if other folders or other document formats are present in the given directory path, it should be able to pick up on pdfs only and create index from it, and ignore the others, just saying...

I actually was thinking about this when writing this bit... To me it felt like a better idea to enforce the folders we want to index to only contain the kind of document we want, since the lib wants accessibility-as-a-first-class-citizen and it'd be confusing for people to expect their other stuff in there to also get picked up (especially if/when we add more document types: how's the user supposed to intuitively know that .ppt will be indexed, but not .docx?). My bigger issue with this is that the error message should be informative though!
