### ISSUE TITLE
load the model in parallel gpu

### ISSUE THREAD

**Issue by bakwankawa** [AnswerDotAI/byaldi#32]
can we load the colpali model in parallel gpu?

**Comment by bclavie** [comment]
What exactly would you want to achieve? There's quite a few meanings to having the model on parallel GPUs:
- Load shards of the model on different GPUs, to minimise memory use
- Load the model on multiple GPUs at once to parallelise processing of a single input as much as possible
- Load multiple instances of the model to different GPUs to break down all the input documents and process them faster on independent model instances.

Ideally we'd want all 3 to be easy to use, though right now the first two are easiest since we're building on top of HF (and therefore have the `device` argument and `device_map`)
