### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by iamkhalidbashir** [AnswerDotAI/byaldi#36]
Is this normal for 1 pdf file with 15 pages for `vidore/colqwen2-v0.1` model

```sh
CUDA out of memory. Tried to allocate 59.39 GiB. GPU 0 has a total capacity of 23.55 GiB of which 11.38 GiB is free. Process 1712302 has 12.16 GiB memory in use. Of the allocated memory 11.25 GiB is allocated by PyTorch, and 473.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

btw I am using following command to encode
```py
embeddings = RAG.model.encode_image(
        input_data=files_to_process,
)
```

**Comment by DebopamParam** [comment]
Hey! I have looked into the code, I'm not really sure why the GPU is getting overloaded. Maybe you ran the script twice with slight configuration changes and it has caused the model to load twice with different configurations. Please try again.


The code is however loading the embeddings into CPU which I just noticed. I don't really understand the nitty gritties of it. If any maintainers can shed some lights to it, it will be very helpful I suppose.
![image](https://github.com/user-attachments/assets/311244a5-eec3-47d0-8249-1565f7050998)

I was able to runvidore/colqwen2-v0.1 successfully in for a 200page pdf successfully.
Here is the notebook file, I hope it might help:

https://colab.research.google.com/drive/1nLqhsio4rUwTUmp7w8YJ0HcGD9Se7hRu?usp=sharing

System requirements: 
- I have run it in on 
![image](https://github.com/user-attachments/assets/776e0405-5fcc-4440-9c03-d870b1ce3701)
on runpod. Make sure you choose 
![image](https://github.com/user-attachments/assets/b0e8d0af-b9fb-4341-b297-f4e0d57d555d)
Otherwise it will not run on older version of cuda. Flash Attention needs is dependent upon torchvision and torchaudio which needs torch>=2.2.0 and cuda>=12.2.0

**Comment by bclavie** [comment]
Hey @iamkhalidbashir, we're definitely missing information to diagnose here. The memory allocation you're experiencing is not normal and is considerably more than needed by the model, so something else is afoot.

For diagnosis, could you provide:
- environment information
- whether or not anything else is running on the machine (and if so, what)?
- full code snippet
Thank you!

**Comment by bclavie** [comment]
Closing as stale for now, but feel free to re-open if you'd like to provide the details above.
